### ISSUE TITLE
Add date and time to received messages

### ISSUE THREAD

**Issue by rmed** [rmed/wat-bridge#1]
When the WhatsApp account receives messages and the program is not running, these are automatically delivered when the listener starts running. However, it is not possible to know when the message was sent in WhatsApp.

It would be useful to know the date and time of the message when it is delivered by the Telegram bot. This could be done, for instance, sending the timestamp when relaying the message to Telegram through the signal.

**Comment by carlosg-gh** [comment]
I'm gonna try to work in this one. Do you have any kind of IRC or communication channel to speak with you, by the way?

**Comment by rmed** [comment]
Awesome, thanks! I don't have any particular communication channel as of yet (apart from email or issues), but I can create a Gitter room or something like that if you want.

**Comment by carlosg-gh** [comment]
That would be nice if you don't mind.

**Comment by rmed** [comment]
Here you go: https://gitter.im/wat-bridge/Lobby

**Comment by SpEcHiDe** [comment]
How to get the timestamp of received message in WhatsApp?

**Comment by usamegolcuk** [comment]
Sorry,i dont no.

2018-01-15 19:02 GMT+03:00 Shrimadhav U K <notifications@github.com>:
