### ISSUE TITLE
What is the new process of bridging since yowsup is sending client key instead of password

### ISSUE THREAD

**Issue by arpitgoyall** [rmed/wat-bridge#17]

**Comment by rmed** [comment]
I haven't been following development of Yowsup, so I'm afraid I can't help you with that...

**Comment by arpitgoyall** [comment]
That means I can't bridge WhatsApp and telegram until you find the solution. Right?

**Comment by rmed** [comment]
Right, the bridge will not work unless the integration with yowsup is updated. However, I don't really have the time to look into it myself (nor do I use WhatsApp nowadays), but I'll gladly accept any pull requests that tackle this issue.

**Comment by roboraptor** [comment]
Hello, I would like to ask what is the current stage of it. 
Does it work? or not?

**Comment by rmed** [comment]
Hi there! As I haven't really touched this project in years, I'm inclined to say it is very unlikely to work.
