### ISSUE TITLE
Country code truncated?

### ISSUE THREAD

**Issue by springjools** [rmed/wat-bridge#6]
The WhatsApp phone must include the country code (only two digits) followed by the number, for instance 49xxxxxxxxx, and the password can be obtained through the Yowsup cli interface.

Which two of the three digits of the country cide do you use? What happens if several countries use the same two first digits in the country code but only differ with the third?

**Comment by rmed** [comment]
I must admit I didn't consider that case when writing the instructions, sorry about that.

What that means is that you should only write the prefix followed by the phone number, with no spaces or additional characters such as `+`. Therefore you should be able to use any country code, as per the instructions on the [yowsup wiki](https://github.com/tgalal/yowsup/wiki/yowsup-cli-2.0), especially considering that the number is used to instantiate the WhatsApp connection.

I'll update the Readme so it's not confusing.

Thanks
