### ISSUE TITLE
Proposition of solve number Ban.

### ISSUE THREAD

**Issue by chiddekel** [rmed/wat-bridge#8]
My proposition to solve the issue with Ban a number is the possibility of using a virtual SIM card.
User will:
1. The choice of a country prefix like +48, etc, etc.

App will:
1. Generate number and add it after the prefix,  Prefix[2 numbers] + [9 numbers]
This cause problem how to generate none existing number. (avoid doubling from existing phone number)

What is a sim card? - it's a memory with simple yet powerful Java applet.
The applet can be generated with Oracle SDK ( Windows machine req. ) 
Link for the Oracle SIM Applet SDK ( The javacard SDK)
This is base for make virtual number.
http://www.oracle.com/technetwork/java/embedded/javacard/downloads/javacard-sdk-2043229.html

**Comment by chiddekel** [comment]
The second problem to solve is adding SMS center for an ability to send SMS thru that center, to support the virtual card and its number.

**Comment by rmed** [comment]
While that seems like an interesting concept, I feel like it's not directly related to the bot itself.

Besides, I don't think it would work, as there's regulation for phone numbers and you can't simply grab one that is not currently active.

**Comment by chiddekel** [comment]
https://www.twilio.com/whatsapp
