### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by HeadlineLPT** [rmed/wat-bridge#9]
I get the following Message:

> [INFO] 2018-11-11 17:36:57,511 - listeners[tg_listener]: Start Telegram polling
> [INFO] 2018-11-11 17:36:57,517 - listeners[wa_listener]: Start Whatsapp polling
> [ERROR] 2018-11-11 17:36:59,964 - listeners[wa_listener]: not-authorized
> [INFO] 2018-11-11 17:36:59,964 - listeners[wa_listener]: Start Whatsapp sleep
> [INFO] 2018-11-11 17:37:09,971 - listeners[wa_listener]: Ended Whatsapp sleep
> [INFO] 2018-11-11 17:37:09,972 - listeners[wa_listener]: Start Whatsapp polling
> [ERROR] 2018-11-11 17:37:10,420 - listeners[wa_listener]: not-authorized
> [INFO] 2018-11-11 17:37:10,420 - listeners[wa_listener]: Start Whatsapp sleep
>

Can anyone help me?

**Comment by rmed** [comment]
Are you able to login using yowsup directly? If so, there may have been a change in the library that may require modifications in the listener

**Comment by HeadlineLPT** [comment]
I can verify my number via Yowsup. I set the token in wat-bridge what yowsup me give.

How do you mean login using yowsup directly?

**Comment by rmed** [comment]
Try using one of the sample applications provided by yowsup (https://github.com/tgalal/yowsup/wiki/Sample-Application)
